apiVersion: v1
kind: ConfigMap
metadata:
  name: energy-rag-config
  namespace: energy-rag
data:
  POSTGRES_DB: energy_rag
  POSTGRES_USER: rag
  LOG_LEVEL: INFO
  EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
  LLM_PROVIDER: ollama
  LLM_MODEL: llama3.1:8b
  LLM_BASE_URL: ""
  OLLAMA_BASE_URL: http://192.168.1.50:11434
  RAG_API_URL: http://api:8000
  FCC_HOST: "0.0.0.0"
  FCC_PORT: "8082"
  FCC_OPEN_BROWSER: "false"
  MESSAGING_PLATFORM: none
